[global]
log_level = 'info'

[mode]

[mode.clients]
enabled = true
refresh = true
misbehaviour = true

[mode.connections]
enabled = false

[mode.channels]
enabled = false

[mode.packets]
enabled = true
clear_interval = 100
clear_on_start = true
filter = true
tx_confirmation = true

[rest]
enabled = true
host = '0.0.0.0'
port = 3000

[telemetry]
enabled = true
host = '0.0.0.0'
port = 3001

[[chains]]
id = 'likecoin-mainnet-2'
rpc_addr = 'http://likecoin-chain-node-fotan-rpc:26657'
grpc_addr = 'http://likecoin-chain-node-fotan-api:9090'
websocket_addr = 'ws://likecoin-chain-node-fotan-rpc:26657/websocket'

rpc_timeout = '60s'
account_prefix = 'like'

key_name = 'relayer'
address_type = { derivation = 'cosmos' }
store_prefix = 'ibc'
memo_prefix = '{your moniker}'
default_gas = 1000000
max_gas = 3000000
gas_price = { price = 10, denom = 'nanolike' }

gas_multiplier = 1.2
max_msg_num = 30
max_tx_size = 2097152

clock_drift = '5s'
trusting_period = '14days'

trust_threshold = { numerator = '1', denominator = '3' }

# 1. `policy` - one of two types are supported:
#       - 'allow': permit relaying _only on_ the port/channel id in the list below,
#       - 'deny': permit relaying on any channel _except for_ the list below.
# 2. `list` - the list of channels specified by the port and channel identifiers.
#
# Example configuration of a channel filter, denying packet relaying on channel with port ID 'transfer' and channel ID 'channel-0':
#
# [chains.packet_filter]
# policy = 'deny'
# list = [
#   ['transfer', 'channel-2'],
# ]
[chains.packet_filter]
policy = 'allow'
list = [
  ['ica*', 'channel-3'],
  ['ica*', 'channel-5'],
  ['transfer', 'channel-3'],
  ['transfer', 'channel-5'],
]


[[chains]]
id = 'osmosis-1'
rpc_addr = 'http://osmosis-node-mainnet-rpc:26657'
grpc_addr = 'http://osmosis-node-mainnet-api:9090'
websocket_addr = 'ws://osmosis-node-mainnet-rpc:26657/websocket'
rpc_timeout = '60s'
account_prefix = 'osmo'
key_name = 'relayer'
store_prefix = 'ibc'
memo_prefix = '{your moniker}'
max_gas = 6000000
default_gas = 2000000
gas_price = { price = 0.000, denom = 'uosmo' }
gas_multiplier = 2
max_msg_num = 30
max_tx_size = 2097152
clock_drift = '10s'
trusting_period = '10days'
trust_threshold = { numerator = '1', denominator = '3' }
address_type = { derivation = 'cosmos' }
[chains.packet_filter]
policy = 'allow'
list = [
  ['ica*', 'channel-53'],
  ['ica*', 'channel-135'],
  ['transfer', 'channel-53'],
  ['transfer', 'channel-135'],
]

[[chains]]
id = 'cosmoshub-4'
rpc_addr = 'http://cosmos-node-mainnet-rpc:26657'
grpc_addr = 'http://cosmos-node-mainnet-api:9090'
websocket_addr = 'ws://cosmos-node-mainnet-rpc:26657/websocket'
rpc_timeout = '60s'
account_prefix = 'cosmos'
key_name = 'relayer'
store_prefix = 'ibc'
memo_prefix = '{your moniker}'
max_gas = 2000000
default_gas = 1000000
max_tx_size = 180000
max_msg_num = 20
gas_price = { price = 0.003, denom = 'uatom' }
gas_multiplier = 1.2
clock_drift ='10s'
trusting_period = '14days'
trust_threshold = { numerator = '1', denominator = '3' }
address_type = { derivation = 'cosmos' }
[chains.packet_filter]
policy = 'allow'
list = [
  ['ica*', 'channel-217'],
  ['transfer', 'channel-217'],
]
